/**
 * google-reviews.js
 * Reads from reviews-cache.json (generated by fetch-reviews.js)
 * and renders real Google review cards on the homepage.
 * API key is NEVER exposed to the browser.
 */

(function () {
    const CACHE_URL      = '/reviews-cache.json';
    const REVIEW_LINK    = 'https://www.google.com/search?q=Disaster+Response+by+Ryan,+3707+Northridge+Dr+NW+STE+10,+Walker,+MI+49544&ludocid=14615414471722616873&lsig=AB86z5X8WiktAHaG3giRLCxRpt11';
    const GOOGLE_LOGO    = `<svg width="18" height="18" viewBox="0 0 48 48" aria-hidden="true">
        <path fill="#4285F4" d="M45.12 24.5c0-1.56-.14-3.06-.4-4.5H24v8.51h11.84c-.51 2.75-2.06 5.08-4.39 6.64v5.52h7.11c4.16-3.83 6.56-9.47 6.56-16.17z"/>
        <path fill="#34A853" d="M24 46c5.94 0 10.92-1.97 14.56-5.33l-7.11-5.52c-1.97 1.32-4.49 2.1-7.45 2.1-5.73 0-10.58-3.87-12.32-9.07H4.34v5.7C7.96 41.07 15.4 46 24 46z"/>
        <path fill="#FBBC05" d="M11.68 28.18A13.9 13.9 0 0 1 10.8 24c0-1.45.25-2.86.68-4.18v-5.7H4.34A23.93 23.93 0 0 0 2 24c0 3.86.92 7.52 2.54 10.76l7.14-5.58z"/>
        <path fill="#EA4335" d="M24 10.75c3.23 0 6.13 1.11 8.41 3.29l6.31-6.31C34.91 4.18 29.93 2 24 2 15.4 2 7.96 6.93 4.34 14.12l7.34 5.7c1.74-5.2 6.59-9.07 12.32-9.07z"/>
    </svg>`;

    const AVATAR_COLORS = [
        '#60a5fa','#fb923c','#4ade80','#eab308',
        '#ef4444','#818cf8','#f472b6','#2dd4bf'
    ];

    function avatarColor(name) {
        let hash = 0;
        for (let i = 0; i < name.length; i++) hash = name.charCodeAt(i) + ((hash << 5) - hash);
        return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
    }

    function starsHTML(n) {
        let s = '';
        for (let i = 1; i <= 5; i++) {
            s += `<i class="${i <= n ? 'fa-solid' : 'fa-regular'} fa-star" style="color:#fbbc05;font-size:.75rem;"></i>`;
        }
        return s;
    }

    function renderCard(r) {
        const initial = r.author_name ? r.author_name.charAt(0).toUpperCase() : '?';
        const color   = avatarColor(r.author_name || '');
        const photo   = r.profile_photo_url || '';
        const text    = r.text ? `"${r.text}"` : '';
        const when    = r.relative_time_description || '';

        const avatar = photo
            ? `<img src="${photo}" alt="${r.author_name}" width="44" height="44"
                    style="border-radius:50%;object-fit:cover;flex-shrink:0;" loading="lazy"
                    onerror="this.style.display='none';">`
            : `<div style="width:44px;height:44px;border-radius:50%;background:${color};display:flex;align-items:center;justify-content:center;color:#000;font-weight:700;font-size:1.1rem;flex-shrink:0;">${initial}</div>`;

        return `
        <div style="background:var(--bg-white);border:1px solid rgba(255,255,255,0.08);border-radius:var(--radius-lg);padding:1.5rem;box-shadow:var(--shadow-md);display:flex;flex-direction:column;gap:1rem;transition:var(--transition-base);">
            <div style="display:flex;align-items:center;gap:.75rem;">
                ${avatar}
                <div style="flex:1;min-width:0;">
                    <div style="font-weight:700;font-size:.9rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#fff;">${r.author_name}</div>
                    <div style="display:flex;gap:2px;margin-top:2px;">${starsHTML(r.rating)}</div>
                </div>
                ${GOOGLE_LOGO}
            </div>
            <p style="font-size:.9rem;color:var(--text-muted);line-height:1.65;flex:1;margin:0;">${text}</p>
            <div style="font-size:.78rem;color:var(--text-light);opacity:0.6;">${when}</div>
        </div>`;
    }

    function render(data) {
        // Update rating badge
        const scoreEl = document.getElementById('gr-rating-score');
        const totalEl = document.getElementById('gr-rating-total');
        if (scoreEl && data.rating) scoreEl.textContent = Number(data.rating).toFixed(1);
        if (totalEl && data.user_ratings_total) {
            totalEl.textContent = data.user_ratings_total + '+ reviews';
        }

        // Render review cards
        const grid = document.getElementById('gr-reviews-grid');
        if (!grid || !data.reviews || data.reviews.length === 0) return;

        const cards = data.reviews.filter(r => r.rating >= 4).slice(0, 6);
        grid.innerHTML = cards.map(renderCard).join('');
    }

    // Fetch the cached JSON (works on localhost and production)
    document.addEventListener('DOMContentLoaded', function () {
        fetch(CACHE_URL)
            .then(r => r.json())
            .then(data => render(data))
            .catch(() => {
                // Silently fail — fallback hardcoded cards already in the HTML
            });
    });
})();
